[global]
; Не уходить в фон (обязательно для Docker)
daemonize = no

; Логи ошибок в stderr (видны в docker compose logs)
error_log = /proc/self/fd/2

; Уровень логирования: alert, error, warning, notice, debug
log_level = notice

; Лимит на количество ядер для процессов
process.max = 128

; Включаем аварийные процессы при переполнении
emergency_restart_threshold = 10
emergency_restart_interval = 1m

; PID-файл
pid = /run/php-fpm.pid